#!/bin/bash

mogrify -resize 968x648 ~/photobooth/*.jpg
montage ~/photobooth/*.jpg -tile 2x2 -geometry +10+10 ~/photobooth/temp_montage.jpg
suffix=$(date +"%y-%m-%d_%H-%M-%S")
cp ~/photobooth/temp_montage.jpg ~/photobooth_final/PB_${suffix}.jpg
sleep 1
lp -d Canon_CP820 ~/photobooth_final/PB_${suffix}.jpg
rm ~/photobooth/*.jpg
